version: "3.9"
services:
  django:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - docker.env.list
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
